[programs.localnet]
anchor_escrow = "7iDKuYGEDgVKqxAzM3GygLeGKgnJxk3jhVyDmiAhSx8h"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/bmstart/work/solana/keys/alice.json"

[provider]
cluster = "mainnet"
wallet = "/home/bmstart/work/solana/keys/alice.json"

# for devnet
# [provider]
# cluster = "devnet"
# wallet = "~/keys/my-keypair.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
